#ifndef CAMERA_PIPELINE_H
#define CAMERA_PIPELINE_H

#ifdef __cplusplus
extern "C" {
#endif

#include "stm32n6xx_hal.h"
#include <stdint.h>

#ifndef CAMERA_PIPELINE_USE_ST_ISP
#define CAMERA_PIPELINE_USE_ST_ISP 0U
#endif

#ifndef CAMERA_PIPELINE_ISP_GEOMETRY_PROBE
#define CAMERA_PIPELINE_ISP_GEOMETRY_PROBE 1U
#endif

#ifndef CAMERA_PIPELINE_SENSOR_640X480_DEBUG
#define CAMERA_PIPELINE_SENSOR_640X480_DEBUG 0U
#endif

#ifndef CAMERA_PIPELINE_RAW_GRAY_DEBUG
#define CAMERA_PIPELINE_RAW_GRAY_DEBUG 0U
#endif

#ifndef CAMERA_PIPELINE_PIPE0_RAW16_DEBUG
#define CAMERA_PIPELINE_PIPE0_RAW16_DEBUG 1U
#endif

#ifndef CAMERA_PIPELINE_PIPE0_RAW10P_DEBUG
#define CAMERA_PIPELINE_PIPE0_RAW10P_DEBUG 0U
#endif

#ifndef CAMERA_PIPELINE_PIPE0_SW_RGB565_DEBUG
#define CAMERA_PIPELINE_PIPE0_SW_RGB565_DEBUG 1U
#endif

#ifndef CAMERA_PIPELINE_PIPE1_RAWBAYER_ONLY_DEBUG
#define CAMERA_PIPELINE_PIPE1_RAWBAYER_ONLY_DEBUG 0U
#endif

#ifndef CAMERA_PIPELINE_PIPE1_DOWNSIZE_820X320_TO_640X240_DEBUG
#define CAMERA_PIPELINE_PIPE1_DOWNSIZE_820X320_TO_640X240_DEBUG 0U
#endif

#ifndef CAMERA_PIPELINE_PIPE1_GRAY_DECIM_ONLY_DEBUG
#define CAMERA_PIPELINE_PIPE1_GRAY_DECIM_ONLY_DEBUG 0U
#endif

#ifndef CAMERA_PIPELINE_PIPE1_GRAY_CROP_ONLY_DEBUG
#define CAMERA_PIPELINE_PIPE1_GRAY_CROP_ONLY_DEBUG 0U
#endif

#ifndef CAMERA_PIPELINE_PIPE1_GRAY_CROP_WIDTH
#define CAMERA_PIPELINE_PIPE1_GRAY_CROP_WIDTH 640U
#endif

#ifndef CAMERA_PIPELINE_PIPE1_GRAY_CROP_HEIGHT
#define CAMERA_PIPELINE_PIPE1_GRAY_CROP_HEIGHT 240U
#endif

#ifndef CAMERA_PIPELINE_SENSOR_BAYER_PATTERN
#define CAMERA_PIPELINE_SENSOR_BAYER_PATTERN 0U /* ISP_DEMOS_TYPE_RGGB */
#endif

#if ((CAMERA_PIPELINE_USE_ST_ISP != 0U) && \
     (CAMERA_PIPELINE_PIPE0_RAW16_DEBUG == 0U) && \
     (CAMERA_PIPELINE_PIPE0_RAW10P_DEBUG == 0U) && \
     (CAMERA_PIPELINE_PIPE1_RAWBAYER_ONLY_DEBUG == 0U) && \
     (CAMERA_PIPELINE_PIPE1_DOWNSIZE_820X320_TO_640X240_DEBUG == 0U) && \
     (CAMERA_PIPELINE_PIPE1_GRAY_DECIM_ONLY_DEBUG == 0U) && \
     (CAMERA_PIPELINE_PIPE1_GRAY_CROP_ONLY_DEBUG == 0U) && \
     (CAMERA_PIPELINE_RAW_GRAY_DEBUG == 0U))
#define CAMERA_PIPELINE_USE_ISP_RUNTIME 1U
#else
#define CAMERA_PIPELINE_USE_ISP_RUNTIME 0U
#endif

#if (CAMERA_PIPELINE_SENSOR_640X480_DEBUG != 0U)
#define CAMERA_PIPELINE_INPUT_WIDTH 640U
#define CAMERA_PIPELINE_INPUT_HEIGHT 480U
#else
#define CAMERA_PIPELINE_INPUT_WIDTH 1640U
#define CAMERA_PIPELINE_INPUT_HEIGHT 1232U
#endif
#define CAMERA_PIPELINE_BAYER2RGB_OUTPUT_WIDTH (CAMERA_PIPELINE_INPUT_WIDTH / 2U)
#define CAMERA_PIPELINE_BAYER2RGB_OUTPUT_HEIGHT (CAMERA_PIPELINE_INPUT_HEIGHT / 2U)

#ifndef CAMERA_PIPELINE_PIPE0_RAW16_CAPTURE_WIDTH
#define CAMERA_PIPELINE_PIPE0_RAW16_CAPTURE_WIDTH 640U
#endif

#ifndef CAMERA_PIPELINE_PIPE0_SHORT_CAPTURE_HEIGHT
#define CAMERA_PIPELINE_PIPE0_SHORT_CAPTURE_HEIGHT 480U
#endif

#ifndef CAMERA_PIPELINE_PIPE0_SW_RGB565_OUTPUT_WIDTH
#define CAMERA_PIPELINE_PIPE0_SW_RGB565_OUTPUT_WIDTH CAMERA_PIPELINE_BAYER2RGB_OUTPUT_WIDTH
#endif

#ifndef CAMERA_PIPELINE_PIPE0_SW_RGB565_OUTPUT_HEIGHT
#define CAMERA_PIPELINE_PIPE0_SW_RGB565_OUTPUT_HEIGHT CAMERA_PIPELINE_BAYER2RGB_OUTPUT_HEIGHT
#endif

#if (CAMERA_PIPELINE_PIPE0_SW_RGB565_DEBUG != 0U)
#define CAMERA_PIPELINE_OUTPUT_WIDTH CAMERA_PIPELINE_PIPE0_SW_RGB565_OUTPUT_WIDTH
#define CAMERA_PIPELINE_OUTPUT_HEIGHT CAMERA_PIPELINE_PIPE0_SW_RGB565_OUTPUT_HEIGHT
#elif (CAMERA_PIPELINE_PIPE0_RAW10P_DEBUG != 0U)
#define CAMERA_PIPELINE_OUTPUT_WIDTH CAMERA_PIPELINE_INPUT_WIDTH
#define CAMERA_PIPELINE_OUTPUT_HEIGHT CAMERA_PIPELINE_PIPE0_SHORT_CAPTURE_HEIGHT
#elif (CAMERA_PIPELINE_PIPE0_RAW16_DEBUG != 0U)
#define CAMERA_PIPELINE_OUTPUT_WIDTH CAMERA_PIPELINE_PIPE0_RAW16_CAPTURE_WIDTH
#define CAMERA_PIPELINE_OUTPUT_HEIGHT CAMERA_PIPELINE_PIPE0_SHORT_CAPTURE_HEIGHT
#elif (CAMERA_PIPELINE_PIPE1_RAWBAYER_ONLY_DEBUG != 0U)
#define CAMERA_PIPELINE_OUTPUT_WIDTH CAMERA_PIPELINE_BAYER2RGB_OUTPUT_WIDTH
#define CAMERA_PIPELINE_OUTPUT_HEIGHT CAMERA_PIPELINE_BAYER2RGB_OUTPUT_HEIGHT
#elif (CAMERA_PIPELINE_PIPE1_GRAY_DECIM_ONLY_DEBUG != 0U)
#define CAMERA_PIPELINE_OUTPUT_WIDTH CAMERA_PIPELINE_BAYER2RGB_OUTPUT_WIDTH
#define CAMERA_PIPELINE_OUTPUT_HEIGHT CAMERA_PIPELINE_BAYER2RGB_OUTPUT_HEIGHT
#elif (CAMERA_PIPELINE_PIPE1_GRAY_CROP_ONLY_DEBUG != 0U)
#define CAMERA_PIPELINE_OUTPUT_WIDTH CAMERA_PIPELINE_PIPE1_GRAY_CROP_WIDTH
#define CAMERA_PIPELINE_OUTPUT_HEIGHT CAMERA_PIPELINE_PIPE1_GRAY_CROP_HEIGHT
#elif (CAMERA_PIPELINE_PIPE1_DOWNSIZE_820X320_TO_640X240_DEBUG != 0U)
#define CAMERA_PIPELINE_OUTPUT_WIDTH 640U
#define CAMERA_PIPELINE_OUTPUT_HEIGHT 240U
#else
#define CAMERA_PIPELINE_OUTPUT_WIDTH 640U
#define CAMERA_PIPELINE_OUTPUT_HEIGHT 480U
#endif

#if (CAMERA_PIPELINE_PIPE0_SW_RGB565_DEBUG != 0U)
#define CAMERA_PIPELINE_OUTPUT_BYTES_PER_PIXEL 2U
#define CAMERA_PIPELINE_OUTPUT_LINE_BYTES (CAMERA_PIPELINE_OUTPUT_WIDTH * CAMERA_PIPELINE_OUTPUT_BYTES_PER_PIXEL)
#define CAMERA_PIPELINE_OUTPUT_FORMAT_NAME "RGB565"
#elif (CAMERA_PIPELINE_PIPE0_RAW10P_DEBUG != 0U)
#define CAMERA_PIPELINE_OUTPUT_BYTES_PER_PIXEL 1U
#define CAMERA_PIPELINE_OUTPUT_LINE_BYTES (((CAMERA_PIPELINE_OUTPUT_WIDTH * 10U) + 7U) / 8U)
#define CAMERA_PIPELINE_OUTPUT_FORMAT_NAME "RAW10P"
#elif (CAMERA_PIPELINE_PIPE0_RAW16_DEBUG != 0U)
#define CAMERA_PIPELINE_OUTPUT_BYTES_PER_PIXEL 2U
#define CAMERA_PIPELINE_OUTPUT_LINE_BYTES (CAMERA_PIPELINE_OUTPUT_WIDTH * CAMERA_PIPELINE_OUTPUT_BYTES_PER_PIXEL)
#define CAMERA_PIPELINE_OUTPUT_FORMAT_NAME "RAW16"
#elif (CAMERA_PIPELINE_RAW_GRAY_DEBUG != 0U)
#define CAMERA_PIPELINE_OUTPUT_BYTES_PER_PIXEL 1U
#define CAMERA_PIPELINE_OUTPUT_LINE_BYTES (CAMERA_PIPELINE_OUTPUT_WIDTH * CAMERA_PIPELINE_OUTPUT_BYTES_PER_PIXEL)
#define CAMERA_PIPELINE_OUTPUT_FORMAT_NAME "GRAY8"
#else
#define CAMERA_PIPELINE_OUTPUT_BYTES_PER_PIXEL 2U
#define CAMERA_PIPELINE_OUTPUT_LINE_BYTES (CAMERA_PIPELINE_OUTPUT_WIDTH * CAMERA_PIPELINE_OUTPUT_BYTES_PER_PIXEL)
#define CAMERA_PIPELINE_OUTPUT_FORMAT_NAME "RGB565"
#endif

#define CAMERA_PIPELINE_ALIGN_UP(V, A) ((((V) + ((A) - 1U)) / (A)) * (A))
#if (CAMERA_PIPELINE_PIPE0_SW_RGB565_DEBUG != 0U)
#define CAMERA_PIPELINE_OUTPUT_PITCH_BYTES CAMERA_PIPELINE_OUTPUT_LINE_BYTES
#else
#define CAMERA_PIPELINE_OUTPUT_PITCH_BYTES CAMERA_PIPELINE_ALIGN_UP(CAMERA_PIPELINE_OUTPUT_LINE_BYTES, 16U)
#endif
#define CAMERA_PIPELINE_FRAME_BYTES \
  (CAMERA_PIPELINE_OUTPUT_PITCH_BYTES * CAMERA_PIPELINE_OUTPUT_HEIGHT)
#define CAMERA_PIPELINE_RGB565_FRAME_BYTES CAMERA_PIPELINE_FRAME_BYTES

#if ((CAMERA_PIPELINE_PIPE0_RAW16_DEBUG != 0U) && (CAMERA_PIPELINE_PIPE0_SW_RGB565_DEBUG != 0U))
#define CAMERA_PIPELINE_PIPE0_RAW_CAPTURE_WIDTH (CAMERA_PIPELINE_INPUT_WIDTH / 2U)
#define CAMERA_PIPELINE_PIPE0_RAW_CAPTURE_HEIGHT (CAMERA_PIPELINE_INPUT_HEIGHT / 2U)
#define CAMERA_PIPELINE_PIPE0_RAW_CAPTURE_BYTES_PER_PIXEL 2U
#define CAMERA_PIPELINE_PIPE0_RAW_CAPTURE_LINE_BYTES \
  (CAMERA_PIPELINE_PIPE0_RAW_CAPTURE_WIDTH * CAMERA_PIPELINE_PIPE0_RAW_CAPTURE_BYTES_PER_PIXEL)
#define CAMERA_PIPELINE_PIPE0_RAW_CAPTURE_PITCH_BYTES CAMERA_PIPELINE_PIPE0_RAW_CAPTURE_LINE_BYTES
#define CAMERA_PIPELINE_PIPE0_RAW_PIPE_CONFIG_PITCH_BYTES \
  CAMERA_PIPELINE_ALIGN_UP(CAMERA_PIPELINE_PIPE0_RAW_CAPTURE_LINE_BYTES, 16U)
#define CAMERA_PIPELINE_PIPE0_RAW_CAPTURE_FRAME_BYTES \
  (CAMERA_PIPELINE_PIPE0_RAW_CAPTURE_PITCH_BYTES * CAMERA_PIPELINE_PIPE0_RAW_CAPTURE_HEIGHT)
#else
#define CAMERA_PIPELINE_PIPE0_RAW_CAPTURE_WIDTH CAMERA_PIPELINE_OUTPUT_WIDTH
#define CAMERA_PIPELINE_PIPE0_RAW_CAPTURE_HEIGHT CAMERA_PIPELINE_OUTPUT_HEIGHT
#define CAMERA_PIPELINE_PIPE0_RAW_CAPTURE_BYTES_PER_PIXEL CAMERA_PIPELINE_OUTPUT_BYTES_PER_PIXEL
#define CAMERA_PIPELINE_PIPE0_RAW_CAPTURE_LINE_BYTES CAMERA_PIPELINE_OUTPUT_LINE_BYTES
#define CAMERA_PIPELINE_PIPE0_RAW_CAPTURE_PITCH_BYTES CAMERA_PIPELINE_OUTPUT_PITCH_BYTES
#define CAMERA_PIPELINE_PIPE0_RAW_PIPE_CONFIG_PITCH_BYTES CAMERA_PIPELINE_OUTPUT_PITCH_BYTES
#define CAMERA_PIPELINE_PIPE0_RAW_CAPTURE_FRAME_BYTES CAMERA_PIPELINE_FRAME_BYTES
#endif

#define CAMERA_PIPELINE_WB_GAIN_1X 100000000U

typedef enum
{
  CAMERA_PIPELINE_STATE_RESET = 0,
  CAMERA_PIPELINE_STATE_SCAFFOLD_READY,
  CAMERA_PIPELINE_STATE_SENSOR_READY,
  CAMERA_PIPELINE_STATE_RUNNING,
  CAMERA_PIPELINE_STATE_FROZEN,
  CAMERA_PIPELINE_STATE_ERROR
} CameraPipeline_State_t;

typedef struct
{
  CameraPipeline_State_t state;
  uint32_t sensor_id;
  uint32_t last_error;
  uint32_t frame_count;
} CameraPipeline_Status_t;

typedef struct
{
  uint16_t exposure_lines;
  uint8_t analog_gain;
  uint16_t digital_gain;
  uint32_t wb_red_gain;
  uint32_t wb_green_gain;
  uint32_t wb_blue_gain;
  uint8_t gamma_enable;
} CameraPipeline_ImageControl_t;

HAL_StatusTypeDef CameraPipeline_InitAndStart(I2C_HandleTypeDef *hi2c);
void CameraPipeline_Task(void);
void CameraPipeline_GetStatus(CameraPipeline_Status_t *status);
uint8_t *CameraPipeline_GetFrameBuffer(void);
uint32_t CameraPipeline_GetFrameBufferSize(void);
void CameraPipeline_GetDefaultImageControl(CameraPipeline_ImageControl_t *control);
void CameraPipeline_GetImageControl(CameraPipeline_ImageControl_t *control);
HAL_StatusTypeDef CameraPipeline_ApplyImageControl(const CameraPipeline_ImageControl_t *control);
void CameraPipeline_PrintPortingNotes(void);
void CameraPipeline_PrintErrorContext(void);

#ifdef __cplusplus
}
#endif

#endif /* CAMERA_PIPELINE_H */



