/* USER CODE BEGIN Header */
/**
  ******************************************************************************
  * @file           : extmem.c
  * @brief          : External memory manager setup for FSBL -> Appli LRUN.
  ******************************************************************************
  */
/* USER CODE END Header */

#include "main.h"
/* USER CODE BEGIN Includes */
#include "extmem.h"
/* USER CODE END Includes */

/* USER CODE BEGIN PD */
/* Header v2.3 generated by STM32 SigningTool is 0x400 bytes. */
#define HEADER_V2_3_IMG_SIZE_OFFSET 108U
#define HEADER_V2_3_SIZE            1024U
/* USER CODE END PD */

/* USER CODE BEGIN 0 */
void MX_EXTMEM_Init(void)
{
  if (EXTMEM_OK != EXTMEM_Init(EXTMEMORY_1, HAL_RCCEx_GetPeriphCLKFreq(RCC_PERIPHCLK_XSPI2)))
  {
    Error_Handler();
  }
}

uint32_t BOOT_GetApplicationSize(uint32_t img_addr)
{
  return (*(uint32_t *)(img_addr + HEADER_V2_3_IMG_SIZE_OFFSET)) + HEADER_V2_3_SIZE;
}
/* USER CODE END 0 */
